ALTER TABLE users
    ADD COLUMN IF NOT EXISTS display_name TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS status_message TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS last_active_at TIMESTAMPTZ;
